### ISSUE TITLE
customLabel for Array options?

### ISSUE THREAD

**Issue by Astray-git** [monterail/vue-multiselect#119]
For now the `customLabel` attribute only works on Object options. Why not allow this on Array options?

**Comment by shentao** [comment]
Made it like this, because if you have an array of primitive values they are probably already descriptive enough and there is nothing inside the options that could be used to create a custom label.
I will look into it, as someone might want to change the label based on the outside of vue-multiselect. Is this your case?

**Comment by Astray-git** [comment]
```
// data
TYPES: [1,2]
TYPE_MAP: {1: 'user', 2: 'admin'}
// methods
customLabel (value) { return this.TYPE_MAP[value] }
```

then I don't need to `find` the preselect object from array, and I can submit the value directly

**Comment by shentao** [comment]
I will work on Multiselect this Sunday so I will look into it. There might be a way to use the customLabel logic for all labels.

Adding to TODO. :)

**Comment by shentao** [comment]
Fixed in both 1.x and 2.0 beta.
