### ISSUE TITLE
[object Object]

### ISSUE THREAD

**Issue by nacr-dev** [monterail/vue-multiselect#121]
Hello,

I'm getting the text [object Object] in all options since I updated to vue-multiselect@1.1.4

What did I do wrong?

**Comment by shentao** [comment]
Aghr. Sorry. I accidentally published an invalid bundle (2.0-beta went to latest instead of --next tag). Fixed it in a hurry, but I didn’t had enough time to double check everything.
Will fix this today!

**Comment by nacr-dev** [comment]
ok, I will wait for it 👍

**Comment by shentao** [comment]
Hey @nacr-dev  I found where is the problem is. Actually, that’s not a bug! 😂 
The method responsible for getting the label has changed to a simpler one that actually makes it possible to create custom labels for non-object options (see #119).
However, this also removed the fallback to `.label` key for getting the object label if the `label` prop is not present. 

I will restore the label fallback shortly. I would however recommend adding the missing `label="label"` prop. :)

**Comment by alexcroox** [comment]
I'm getting [object Object] when passing this as the options:

[{label: "english", value: "en"}]

![ss](https://cl.ly/k5eH/Screen%20Shot%202017-04-20%20at%2010.41.13.png)
