### ISSUE TITLE
Can't select more than one option on multiselect

### ISSUE THREAD

**Issue by SigalZ** [monterail/vue-multiselect#126]
Hi,

When I try to select more than one option I get this error:

[Vue warn]: You are setting a non-existent path "selected" on a vm instance. 
Consider pre-initializing the property with the "data" option for more reliable reactivity and better performance.

You can see my code here: [http://laravel.io/bin/XyK1Q](http://laravel.io/bin/XyK1Q)

What am I doing wrong?

Thank you

**Comment by shentao** [comment]
Hey :) 

Your prop `:selected="multiValue"` should be changed to `:selected="selected"`. MultiValue does not exist in your component. 

Also, your drop-down component lacks the way to sync the data back to the parent component, where it should be handled. I wouldn’t recommend using the reference as a way to do two-way binding.

**Comment by SigalZ** [comment]
Thank you shentao, can you please explain more about what you mean here: "Also, your drop-down component lacks the way to sync the data back to the parent component, where it should be handled. I wouldn’t recommend using the reference as a way to do two-way binding. " I'm really new to Laravel and Vue and really struggling here. Can you give me an actual code example of what you mean please?

**Comment by shentao** [comment]
So you have a wrapper `drop-down` component that you feed with the `:options`. It also has a `:selected` prop. However, if you use the dropdown in context of a form. Let’s say you have a form object like this:
```
data () {
  return {
    myFormObj: {
      name: '',
      selected: '',
      age: null
    }
  }
}
```
And you passed the `selected` value to the dropdown’s `:selected` prop. Multiselect has the `@update` event that you use to update the property. That’s because Multiselect on it’s own, will not mutate the selected prop he gets. That’s why you have to react to the `@update` event and mutate it yourself in the `updateSelected` method. You will need something similar to update the `selected` prop of the `drop-down` wrapper component so that the parent knows that the dropdown’s value has changed. 

This means that your parent would need to be changed to something like this:
```
<div class="form-group">
 <drop-down
      :options="{{ $members_list->toJson() }}"
      :selected.sync="selected"
  ></drop-down>
</div>
```

or similar to how mutliselect works:
```
<div class="form-group">
 <drop-down
      :options="{{ $members_list->toJson() }}"
      :selected="value"
      @update="updateSelectedValue"
  ></drop-down>
</div>
```
In the second case, your `updateSelected` method would need this additional line:
`this.$emit('update', this.selected)`. 

The thing is. If you don’t use `.sync` (Vue 1.0 only, in 2.0 it is deprecated). Only objects will sync back to the parent component because they are passed as reference. If the values happen to be primitives like strings or numbers, they won’t be updated in the parent data. They will be treated as one-way-down props.
Does that makes sense? There is a lot about it in Vue.js docs.

**Comment by SigalZ** [comment]
Thank you. I made the changes and now the select is not even populated with the members.
Code: http://laravel.io/bin/Nklbv

Maybe I should just give it up and use plain jQuery instead. Thanks

**Comment by shentao** [comment]
http://laravel.io/bin/E3we9

**Comment by SigalZ** [comment]
Thank you very much. But the code you sent me gives this error: ReferenceError: DropDown is not defined
DropDown

**Comment by shentao** [comment]
You have to import it. But that’s only true if you use browserify/webpack. If not, skip the
```
components: {
  DropDown
}
```
part. You should then have the DropDown registered globally.

**Comment by SigalZ** [comment]
Thank you, you are very kind to help so much.

**Comment by shentao** [comment]
No a problem :)
