### ISSUE TITLE
Two-Way Databinding

### ISSUE THREAD

**Issue by smith64fx** [monterail/vue-multiselect#161]
Version 2.0-Beta-10

Hey man, awesome work :) So far I didn't have any problems, just this little one.

When I set the :selected property manually from outside, the tags are not updated properly.. Is there any workaround needed for this?

**Comment by dannydombrowski** [comment]
Hey!

You should look at the following :

For Vue 2.0 users:

Vue-multiselect 2.0-beta is available: npm install vue-multiselect@next. API changes:

Instead of Vue.partial for custom option templates you can use a custom render function.
The :key props has changed to :track-by, due to conflicts with Vue 2.0.
Added support for v-model
@update has changed to @input to also work with v-model
**:selected has changed to :value for the same reason**

**Comment by shentao** [comment]
For 2.0 version you have to use the `:value` prop instead of `:selected`. Additionally, for two-way data binding, you can now use `v-model` just like you would with a simple input :)
