### ISSUE TITLE
Allow label attribute to be a computed value

### ISSUE THREAD

**Issue by kubakrzempek** [monterail/vue-multiselect#17]
The `label` attribute can only evaluate to prop from passed in object, but it would be super cool if it could take a computed value from multiple props.

**Comment by shentao** [comment]
I have a draft that would enable providing a function that would return an interpolated string with whatever needs to be shown in the options list / result.

Should be implemented soon. :)

**Comment by jpmurray** [comment]
That will be perfect! Because at this point, on my end, my label is a composite value of two columns, but I  concatenate them on the server side then return the string as the label to the front end. Problem is, the string looks like `Some name - Some title`. So, searching for "Nirvana spirit" will send the right query, and return the good result from the server, but I won't be able to search/find for "Nirvana - Smells like teen spirit" in multiselect's unless I type it all, including the `-`.

So, if I'm not mistaken, what you are working on should be me in that case, @shentao ?

**Comment by shentao** [comment]
Yes @jpmurray! :) You will be able to pass something like `${artist} - ${title} (${album})` as label. But searching will be working based on all keys.

**Comment by kubakrzempek** [comment]
That's somehow the same issue/need we've faced. :)

**Comment by shentao** [comment]
@jpmurray Merged and available in v0.2 :)
