### ISSUE TITLE
Consider not using 'let'

### ISSUE THREAD

**Issue by jbardnz** [monterail/vue-multiselect#22]
I was having issues running my code in FireFox and traced the issue back to the use of 'let' in this plugin. My FF was a couple of versions out of date and I noticed support for let is still not great, it was only supported in Chrome/FF as of a couple of versions ago and Safari/IE 10 has no support for it. 

http://caniuse.com/#feat=let

Would you consider not using let so this plugin can support older browsers?

**Comment by shentao** [comment]
Hey @jbardnz!
This should not happen since version v0.2 (released last night), as the plugin is now loaded as an babel transpiled umd bundle, which means all `let` uses are transpiled to `var`.

This means vue-multiselect should support browsers **down to IE 9**. :)

I added the `/lib` directory to the repository as this is where the package.json `main` key points to.

**Please update to the newest version and let me know if this fixes the problem**.

Additionally, keep in mind, that v0.2 introduces a minor breaking change in importing.
Instead of:
``` javascript
import Multiselect from 'vue-multiselect'`
```
you have to use object destructuring
``` javascript
import { Multiselect } from 'vue-multiselect'`
```

It is worth noting that you can now also import just the mixins and construct your own select components based on them. You can do this like this:
``` javascript
import { multiselectMixin, pointerMixin } from 'vue-multiselect'`
```
