### ISSUE TITLE
Bulma Modal scrolling problem

### ISSUE THREAD

**Issue by xereda** [monterail/vue-multiselect#239]
Ref: issue - #227 

The problem using "overflow: visible;" In a Bulma modal is that I can no longer scroll when the form is larger than the screen layout.

What I effectively need is that scrolling within the modal works and that "vue-multiselect" is over all elements.

Look at the illustrations below:

![bulma_modal](https://cloud.githubusercontent.com/assets/14337850/22530737/3721e982-e8c4-11e6-852d-97fbb3f79fb6.gif)

**Comment by shentao** [comment]
Due to how vue-multiselect works, it’s not possible to fix this on the components side, at least for now. The reason for it is that the dropdown list is rendered next to the element instead of ported to the root DOM element. This means it is limited by the same overflow rules that all other elements in your div (in this case the bulma model container).
I would suggest trying to move the dropdown to the top or change the way the modal works.

**Comment by adam-lynch** [comment]
Is there any way this can be achieved via config? For example, Select2 allows you to pass a parent element. I'd be open to making a PR.

> change the way the modal works

I can't see a way to change the (scrollable) modal to make it work. Can you?
