### ISSUE TITLE
Error, If there are no options available and click Enter

### ISSUE THREAD

**Issue by sellvana** [monterail/vue-multiselect#243]
Hello, getting this error:
```
Uncaught TypeError: Cannot read property 'isLabel' of undefined
    at VueComponent.addPointerElement (vue-multiselect.js:1)
    at Array.<anonymous> (vue-multiselect.js:1)
    at HTMLInputElement.<anonymous> (vue-2.1.8.js:2221)
```
Thanks.

**Comment by sellvana** [comment]
Also, got this one when selecting a value...

`[Vue warn]: You may have an infinite update loop in watcher with expression "internalValue" 
(found in component <vue-multiselect>)`

**Comment by sellvana** [comment]
Also, when unselecting (not multiple):
```
Vue warn]: Error when rendering component <vue-multiselect>: 
warn @ vue-2.1.8.js:525
Vue._render @ vue-2.1.8.js:3103
(anonymous) @ vue-2.1.8.js:2464
get @ vue-2.1.8.js:1663
run @ vue-2.1.8.js:1732
flushSchedulerQueue @ vue-2.1.8.js:1548
(anonymous) @ vue-2.1.8.js:477
nextTickHandler @ vue-2.1.8.js:426
2017-02-04 23:45:47.917 vue-2.1.8.js:439 TypeError: Cannot read property 'id' of null
```

**Comment by sellvana** [comment]
Should I open them as separate issues? I'm just not sure if they're real issues or my misunderstanding how it suppose to work...

**Comment by shentao** [comment]
The second one should be fixed after I finally release the new version. Sorry for the delay, I had to change apartments last week so I had no time to work on multiselect. Hope to do it this week.

**Comment by Christilut** [comment]
Same error here. Happens when you press enter when tag input field is empty.

Here is my full component: https://gist.github.com/Christilut/3ae5fa966ee2cec6358f7642a3d6b75a

**Comment by shentao** [comment]
I hope to release it this weekend. Sorry for the delay.

**Comment by shentao** [comment]
@Christilut @sellvana beta.14 released and should fix this problem. Sorry you had to wait so long :(
Please read: https://github.com/monterail/vue-multiselect/blob/2.0/README.md
Breaking change regarding the styles.

**Comment by Christilut** [comment]
No worries, thanks for your hard work 👍

**Comment by unirgy** [comment]
Thank you for hard work! Just to confirm, all 3 errors should be fixed, or only some of them?

**Comment by shentao** [comment]
@unirgy all 3 should be fixed. I say should because some of those problems were connected with different issues that I fixed with this release. 
I also want to change the release flow in this project to CD and publish whatever is merged to a new dev branch as new beta/nightly/dev releases and at least once a month push a new version to master with a stable version. Also the current master will be moved to 1.x branch as there is no further development there. I might however merge new PRs there and release the 1.x version given community contributions. Though I would recommend migrating to 2.x.
