### ISSUE TITLE
Highlight the matching text from query in options(make it bold or some styling option).

### ISSUE THREAD

**Issue by roylkng** [monterail/vue-multiselect#254]
At present I don't see any feature to highlight or to let user know the matching string from the options. If there is there any easy way to do it please point me in that direction. I am already using the custom template for the options.

**Comment by shentao** [comment]
I guess you could use a combination of custom templates (scoped slots) and customLabel (or implement it yourself inside the scoped slots). Using the `@search-change` event you can get the search query text which can be used to highlight parts of the options.

Well, this is how I would approach it at least. I hope it helps! :)

**Comment by roylkng** [comment]
I tried that but custom templates does not take html as input, only possible way I see is getting html of dropdown options and and replacing it with highlighted one in the end of @seach-change function call, which is not a clean approach.

**Comment by shentao** [comment]
CustomLabel doesn’t take html as input – it’s a function that takes the option as the param.
However, there are custom templates for which you can use scoped slots: https://vuejs.org/v2/guide/components.html#Scoped-Slots

Which then can be used like this:
```
<template slot="option" scope="props">
  <span v-html="highlightPhrase(props.option.title)"></span>
</template>
```

where the `highlightPhrase` is a function on your parent component:
```
highlightPhrase (text) {
  if (!this.search.length) return text
  return text.replace(this.search, `<strong>${this.search}</strong>`)
}
```

This should work. Be careful though as this uses `v-html` which might not be the safest solution considering XSS. Because of this it would be better to create a functional component for highlighting text. :)

**Comment by wickkidd** [comment]
@shentao your suggestion works. Thanks. I think that highlighting is such a common and natural feature for autosuggests that it might be worth adding. /2¢
