### ISSUE TITLE
Nested items?

### ISSUE THREAD

**Issue by Blizzke** [monterail/vue-multiselect#258]
Do you think it would be possible use this component if nested functionality is required?
We have too many options to use the regular grouping and were hoping to use it "navigation style":

![screen shot 2017-02-10 at 12 51 52](https://cloud.githubusercontent.com/assets/231572/22825975/495d14d2-ef90-11e6-8d6c-062c72df0f05.png)

Have a bit of doubt on how to best start on this, hopefully it can be done. The rest of this component is 100% what I was looking for so it would be a shaming if I'd have to go looking for something alternative.

**Comment by shentao** [comment]
Hey!

Hm hm, I guess this could be done, but I’m not sure if this is something that should be done using vue-multiselect. Well unless you need many of the features from Multiselect.

If this is the case I would probably use the custom option templates feature (based on scoped slots) and I would disable the `:internal-search="false"`. That’s because when using groups, the internal search mechanism automatically flattens the results. To get the result you showed, they have to stay grouped. Then you need a component for each option to recreate an additional dropdown on hover/focus. Still, there might be a problem with selecting, as the whole slot has an `@click` event listener attached. :/

A different approach would be to build a similar component and use the `multiselectMixin.js` and `pointerMixin.js` mixins. This way you don’t have to recreate some of the logic inside of Multiselect and only work on the template. The `Multiselect.vue` file is an example by itself on how to use the mixins.

However, if you don’t intend to use many of multiselect’s functionalities or the component is very specific in that it doesn’t require lots of customization between use cases then I guess you would be better off with a custom solution.

I hope this helps! :)

**Comment by KRaymundus** [comment]
Facing a similar issue. I was wondering if @Blizzke had any results on either of the approaches?
