### ISSUE TITLE
Scroll Broken in Chrome

### ISSUE THREAD

**Issue by JeremyBYU** [monterail/vue-multiselect#31]
First off, great project! I seem to be having a little problem with scrolling though.

Problem: Can not scroll through options list by using mouse to drag scroll bar.  You have to use the mouse wheel.

Environment:
vue-multiselect: "^0.2.3"
NodeJS 4.X
OS: Windows
Browser: Chrome Version 51.0.2704.84 m
No external styles being used.

Gif of problem:
![multi-select-dropdown](https://cloud.githubusercontent.com/assets/6628085/15988556/0d89b5da-301b-11e6-9898-24279e86e090.gif)

I tried this on the Edge browser and it worked just fine! Must be something specific to chrome.

**Comment by shentao** [comment]
Weird! Must be a problem with Chrome on Windows, because on OS X it works without any problems.

**Comment by JeremyBYU** [comment]
It could be my set up, I'm still looking into it and will let you know if I can think of anything!

**Comment by JeremyBYU** [comment]
Got some good news about tracking down the bug!
I git cloned this repository and `npm install && npm run dev`. I noticed I was experiencing the **same** problem on your localhost homepage on this component:
![image](https://cloud.githubusercontent.com/assets/6628085/15991967/c31f15f0-3086-11e6-9fd7-9cf61f7fd46b.png)

However the problem was **not** happening on the primitive value example component:
![image](https://cloud.githubusercontent.com/assets/6628085/15991968/e5f8b09a-3086-11e6-8cdc-81d69ccc8328.png)

I looked at the code to see the difference and the culprit prop is: `searchable`.  Once you add the prop it seems like this bug is introduced.  I tested this by going back to my original project and making` searchable=false` and it worked!

Not sure why this bug occurs on chrome windows on master branch but I'm guessing something to do with click event?  Not sure, but I hope this helps in some way.

**Comment by shentao** [comment]
Well, this looks like it loses the focus for a moment, thus triggering a close and open events. Changing `searchable` to `false` removes this problem because then we focus the container instead of the search input. Because the scrollbar is a shown on a child element of an already focused element, it doesn’t lose focus. But when we use the search input, it doesn’t have any children (hence, it’s an input).

Have you tried it in Firefox?

**Comment by JeremyBYU** [comment]
I downloaded firefox and gave it go. It is showing the same issue as Chrome.

Firefox Version: 47.0

What your saying makes sense about the loss of focus.

**Comment by victor-ponamariov** [comment]
I have exactly the same issue on chrome and firefox

**Comment by shentao** [comment]
I’m not sure how to actually fix it, but I will try. I’m afraid this might require large changes in the component template. Hope it isn’t crucial for you :/

**Comment by thoughts1053** [comment]
I'm also having the issue on Chrome for Windows. I haven't tested other browsers but want to be subscribed to replies.

**Comment by JeremyBYU** [comment]
Just added a pull request that I believe should fix this issue.  Would appreciate anyone's help on testing for MacOS and Linux (as well as Windows to double check my testing)

**Comment by shentao** [comment]
Tested on MacOS, works like a charm. 💃 

Thank you very much for your contribution. It was merged manually and will be released in v0.2.4 in a moment.

**Comment by JeremyBYU** [comment]
Thanks! I'm glad it worked out.

**Comment by shentao** [comment]
I just noticed there are problems with the TAB button now, related to the refocusing of search field. :/

**Comment by JeremyBYU** [comment]
Doh!!! I never tested tabs! Sorry about that.  Where should it focus on then?

**Comment by shentao** [comment]
It would be best if it didn’t lose focus in the first place. It works with `v-show` and a transition because the elements are stil there when you click on the scrollbar. With `v-if` the node is gone.
For now, I will revert both your and my solutions with the change to `v-if`. This should temporary fix the problem with the scroll bar, giving us time to find a better solution.
The performance problem might not be all that important considering I had problems with it only when I initialized 255 multiselects components with 255 options each. 😃

**Comment by JeremyBYU** [comment]
Sounds good. I think thats' the right decision for now.
