### ISSUE TITLE
Asynchronous select: Delay before querying?

### ISSUE THREAD

**Issue by bjmc** [monterail/vue-multiselect#316]
I'm trying to use Vue-Multiselect as a typeahead suggest list that searches using an API as the user enters data. However, I'd rather not slam the API with requests on every keystroke. Is there a way to introduce a delay of N ms after the user stops typing before doing the search? If not, can I make a feature request for future versions?

For reference, I'm following [this example in the docs.](http://monterail.github.io/vue-multiselect/#sub-asynchronous-select)

I'm imagining something like [the `delay` option in Vue-strap typeahead.](http://yuche.github.io/vue-strap/#typeahead)

**Comment by ianrothmann** [comment]
I would just debounce the function that calls the API. Have a look at this thread https://forum-archive.vuejs.org/topic/5174/debounce-replacement-in-vue-2-0/3

**Comment by shentao** [comment]
The solution suggested by @ianrothmann is the recommended approach. :) I use it in my projects the same way.

**Comment by shentao** [comment]
@jdrydn  ¯\_(ツ)_/¯

**Comment by Fusseldieb** [comment]
Frustrated that this isn't implemented by default. Well then...

**Comment by shentao** [comment]
@Fusseldieb it’s a rather easy thing to implement. Why should it be present by default and thus opinionated? There might be different other requirements for the API to be called, not just one based on debounce. Also that delay is likely only useful for lists that are asynchronous, otherwise why would you want the user to wait?
