### ISSUE TITLE
Track by multiple field?

### ISSUE THREAD

**Issue by mwei0210** [monterail/vue-multiselect#319]
As the title says, is it possible?

**Comment by shentao** [comment]
If I understand you correctly, you want to compare elements based on more than one property, is that correct?

This is not possible right now.

However, I guess you might try a workaround and enhance the options objects by using a computed property so that it combines several fields into one unique field. For example:
```
// options list
options: [
  { x: 5, y: 10, z: 15 },
  { x: 5, y: 15, z: 15 },
  { x: 5, y: 25, z: 35 }
]

// enhanced option list as computed
enhancedOptions () {
  return this.options.map(o => ({ ...o, combinedField: o.x + o.y + o.z }))
}
```

Then you should be able to pass `combinedField` as the `track-by` property.

**Comment by mwei0210** [comment]
Sorry for not making it clear. What I meant was, is it able to search by multiple attribute. Eg. search by name and email.

**Comment by shentao** [comment]
Sure! You can use a custom search function by disabling `internal-search` and handling the `@search` event.

**Comment by mwei0210** [comment]
Correct me if I am wrong. But similar to your previous answer, I could pass another filed in the object that joins both name and email, then make label="NameEmail" right? And it's less resource heavy isn't it?

**Comment by shentao** [comment]
Not yet possible as the internal search uses `this.label` instead of customLabel. This might be a nice idea to enhance the search.

**Comment by imcvampire** [comment]
@shentao Can I create a PR to add this feature (compare elements based on more than one property)?

**Comment by shentao** [comment]
@imcvampire Just finished searching based on the customLabel.

**Comment by mwei0210** [comment]
@shentao Thanks man!
