### ISSUE TITLE
directly binding v-model to a property of options

### ISSUE THREAD

**Issue by awesomektvn** [monterail/vue-multiselect#359]
Hi, when the options are an array of objects, for example:
```
options = [
{name: 'a', label: 'Apple'},
{name: 'b', label: 'banana'}
]
```
Is there a way to directly bind the v-model to the key value ( 'name' in this case), instead of binding to the object ?

**Comment by yoavpe1** [comment]
Need this feature too

**Comment by shentao** [comment]
This is not possible.

**Comment by Zip753** [comment]
This issue is a little bit old, so I'm going to close it.

As @shentao mentioned, this is not possible, however you can most probably achieve the desired effect by binding `v-model` to the option object itself (say `v-model="selectedOption"`) and then create a computed value that would extract the desired property from the bound option:
```javascript
computed: {
  selectedOptionName () {
    return this.selectedOption.name // or whatever you want really
  }
}
```

If you meant something else, feel free to open another issue with hopefully better description of what you would like to achieve.
