### ISSUE TITLE
how to change style css

### ISSUE THREAD

**Issue by gyamxxx** [monterail/vue-multiselect#375]
Hi, I'm using bulma.css.
How can I change the look like bulma.css select menu ?
https://jsfiddle.net/c4L3gs91/180/

**Comment by shentao** [comment]
Hey. If you look into the JSFiddle external resources you will notice the of vue-multiselect.min.css file. This is where the CSS is stored. Instead of using it you can provide your own CSS. However, take into account that you have to replicate most of the structure to make it work. Shouldn’t be hard though.

**Comment by megapctr** [comment]
Though it would be nice if the basic things like colors or paddings were easy to configure. One way to do so is to provide a Sass file (and maybe convert it to Less for the few Less users out there) with configurable variables

**Comment by coderabsolute** [comment]
Not sure has anyone changed the style to suit Bulma?
