### ISSUE TITLE
Possible to remove tags? 

### ISSUE THREAD

**Issue by Tyrannas** [monterail/vue-multiselect#390]
It's possible to add new tags, but is it possible to remove them? Can't find where to modify this. 

Thanks.

**Comment by shentao** [comment]
You mean, remove them from the list? This would require to manually handle the `@input` and `@tag`, `@select` events instead of using `v-model`. Then you should be able to find if the option passed to `@select` is a previously created tag, which you can then remove from the `:options`.
I hope that helps. :)
