### ISSUE TITLE
prevent option from selecting.

### ISSUE THREAD

**Issue by ejlocop** [monterail/vue-multiselect#408]
Hello,

i want to prevent user from adding the last selected option from the item.  
so basically i want to remove an option dynamically. 
but it seems like a weird bug. here's repro link.
https://jsfiddle.net/c4L3gs91/264/

**Comment by shentao** [comment]
Hey! You must add `this.$nextTick` to make it work. This is probably due to the order of when the events are triggered. Example: https://jsfiddle.net/cyxbdaez/

Another solution would be to use `@input` instead of `v-model` and prevent the new option to be added if one already exists with the same role. That would remove the need of `$nextTick`.
