### ISSUE TITLE
Why does it always remove the last item?

### ISSUE THREAD

**Issue by maryheng** [monterail/vue-multiselect#438]
Hi all,

I'm new to Vue!

I'm having a problem whereby if I click "X" on the first item, it deletes the last item. The expected behaviour is, clicking on the "X" on the first item, it should remove the first item. I'm not sure how to go about fixing this.

Here is the fiddle:
https://jsfiddle.net/maryheng/c4o5eymv/

I have read what other people have done but I don't really understand...

**Comment by pczarn** [comment]
@maryheng hi and welcome to Vue.

Multiselect needs a `track-by` property to know how to distinguish object items. In your example, you need to add the following line as an attribute for `<multiselect ...>`

```
track-by="subCategoryName"
```

Also take a look at http://monterail.github.io/vue-multiselect/#sub-single-select-object.

I didn't create multiselect, so I'm not sure what is the reason `track-by` exists in the first place. In JavaScript we have this odd behavior that different object instances are not equal (`{} !== {}`), so I guess comparing by primitive values instead of by entire options is better for correctness.

**Comment by maryheng** [comment]
@pczarn Thanks for your help! It works! Now I have a better understanding 👍
