### ISSUE TITLE
With :taggable="true", you can add the same new tag multiple times

### ISSUE THREAD

**Issue by Hillcow** [monterail/vue-multiselect#440]
As it doesn't make much sense, you shouldn't be able to do so.

Thank you!

**Comment by rickbolton** [comment]
Can you give more specifics to what your issue is. e.g. my example here works fine because the track-by (the value) is the same as tag name and so it correctly asks if you'd like to remove it

<img width="865" alt="screen shot 2017-07-19 at 10 16 36" src="https://user-images.githubusercontent.com/10371256/28359882-a0b65880-6c6b-11e7-9959-97a3309d778f.png">

**Comment by Hillcow** [comment]
Hm, what if you add a tag inbetween that is different?

**Comment by rickbolton** [comment]
Can you show me an example of what you're trying to do. Are you using a custom label?

**Comment by mattkoch614** [comment]
I'm seeing this with a set of tags that aren't objects, and hence no ``track-by`` property. I'm using a simple array of strings, and I can add the same one multiple times.
