### ISSUE TITLE
How can I display the user's gender?

### ISSUE THREAD

**Issue by tweaker** [monterail/vue-multiselect#449]
How can I display the user's gender? If the value of `profile.sex = 2` is digital:

```
<multiselect @select="updateSex"
         :value="profile.sex"
         :options="[{sex: 1, label: 'female'}, {sex: 2, label: 'male'}]"
         :searchable="false"
         :allow-empty="false"
         placeholder=""></multiselect>
```

**Comment by Zip753** [comment]
You have to specify `label="label"`. Also keep in mind that `value` prop is the whole object, not just `sex` field. Please read [the documentation](http://monterail.github.io/vue-multiselect/#sub-single-select-object) more thoroughly, it's all written there.

P.S. You should also specify `track-by` prop, so that your objects are distinguishable. In your case `track-by="sex"` should be fine.
