### ISSUE TITLE
Label For ID: Does not work unless multiselect is searchable

### ISSUE THREAD

**Issue by jettoki** [monterail/vue-multiselect#482]
When multiselects are given **label for="thing"** with **multiselect id="thing"**, the label does not open the multiselect field unless the multiselect is flagged as searchable. It looks like the associated input field doesn't exist inside the multiselect component unless it's flagged as searchable.

Repro fiddles:

**Searchable (label working)**
https://jsfiddle.net/7ma9xuvp/1/

**Unsearchable (label not working)**
https://jsfiddle.net/7ma9xuvp/2/

**Comment by shentao** [comment]
Never tried it, but I’m not sure if a label can trigger focus on something different that an `input`. You can open the multiselect yourself using the by adding `ref="multiselect` and then doing `this.$refs.multiselect.focus()`.

**Comment by DM2489** [comment]
This isn't really invalid; its an actual problem from an accessibility perspective.

For me, it's not about providing focus, it's about having the multiselect add the ID parameter properly so that the label is properly connected.

With `searchable="false"` the given `id` is not passed to the underlying input element. This is an issue for assistive technologies and goes against the use of labels in forms.

Are you saying we should not use labels on multiselects where `searchable="false"`?

**Comment by DM2489** [comment]
Looking underneath the hood in a bit more detail, it seems that there is no `input` when `searchable="false"`, so  I guess, technically the current implementation is correct.

From a user perspective though, this is just a select and it would be expected to be accessible.

For the time being I'll just allow the field to be searchable. Not ideal in my circumstances but it best fits from an accessibility point of view.
