### ISSUE TITLE
Images for the select options?

### ISSUE THREAD

**Issue by zachleigh** [monterail/vue-multiselect#50]
Is there currently a way to get images in the select options? Ive been trying to get it working, but I havent found a way yet.  If images arent supported, is there a way to set a class or id on each option so that I could try to find a css solution?     
    
Not a deal breaker, but it would be nice if the package supported this :)

**Comment by shentao** [comment]
If I'm right, then after porting it to support Vue 2.0, it would be easier to support custom option templates (as this would be just a render function then). Supporting Vue 2.0 is something I want to achieve in the next 2 weeks, so this is when I could add support for custom option templates. The current Slot implementation does not enable that, as it is compiled within the parent's scope.

Right now this (and much much more) is already possible if you create a custom component that uses multiselect's mixins. All the javascript code not related to the default template is encapsulated in mixins. What you have to do to make it work:
1. Look into multiselect.vue component.
2. Copy the template and css code to your new custom multiselect component.
3. Change it so that it suits you (handling images in options).
4. Import fhe ```{ multiselectMixin, pointerMixin }``` like in the Readme and add it to your component.
5. Customize the template and css however you like. Just make sure you don't remove any bindings from the template that you actually need.
6. Have fun!

This is not the ideal solution but gives you all the freedom to customize the component and still be up to date with most of the fixes (as those happen mostly within multiselectMixin file).

If you decide to follow this path, I would be happy to see the customized result! We could then create an examples catalog with different **skins** for multiselect.

Next week I would probably create some such examples myself.

**Comment by zachleigh** [comment]
Thanks for your detailed reply, shentao! Ive got it basically working, just need to iron out a few small problems and clean it up a bit. Once I get it all working, Ill let you know.

**Comment by shentao** [comment]
Glad to hear that! Would love to see it live!

**Comment by shentao** [comment]
@liamcharmer Yes. You can use either the `tag` or `selection` slot to modify how the selected elements look like. You can also use the `option` slot to change how the options in the list look like. See the docs for examples (cmd/ctrl+f).
