### ISSUE TITLE
[Suggestion] create 'selecting' and 'removing' events with callback to prevent action.

### ISSUE THREAD

**Issue by jaketoolson** [monterail/vue-multiselect#501]
I'd like to suggest adding 2 emitters that allow a user to hook into them and prevent propogration.  For example, when a user removes a "tagged" item, I am listening to this event and using ajax deleting it on the backend end.  If this fails, I don't want this tag to be removed.

```
const doit = true;

this.$emit('removing', (callback)=>{
   doit = !(callback === false)
});

if (doit) {
   // 
}

```

an example listener would then have the ability to do this:
```
this.$on('removing', (callback)=>{
    axios.delete(url).catch((error)=>{
        return callback(false);
    });
});
```

Now I can control whether multiselect so actually remove the tag:
```multiselectMixin.js```:

```
removeElement (option, shouldClose = true) {
      /* istanbul ignore else */
      if (this.disabled) return
      /* istanbul ignore else */
      if (!this.allowEmpty && this.internalValue.length <= 1) {
        this.deactivate()
        return
      }
      
      const allowRemoval = true;
      this.$emit('removing', (callback)=>{
            allowRemoval = !(callback === false)
      });

     if (!allowRemoval) return

      const index = typeof option === 'object'
        ? this.valueKeys.indexOf(option[this.trackBy])
        : this.valueKeys.indexOf(option)

      this.internalValue.splice(index, 1)
      this.$emit('remove', deepClone(option), this.id)
      this.$emit('input', this.getValue(), this.id)

      /* istanbul ignore else */
      if (this.closeOnSelect && shouldClose) this.deactivate()
    },
```

**Comment by shentao** [comment]
I think this will make the thing too complicated (as child components are not aware that something is listening to selected events), so that would require additional props to set this up.
Also, that would make it more complex because it would require a functionality to actually make selections asynchronous.

What I could recommend you is to extend the VueMultiselect component and override some of the methods, namely `select` method to implement asynchronous selects. That should be rather easy and you would have the freedom to make it just as the feature requires.

I’ve also looked into the PR. Leaving a comment there.
Thanks for the suggestion! It might be easier to do once I figure out the 3.0 release. :)
