### ISSUE TITLE
Set value / label of Asynchronous select

### ISSUE THREAD

**Issue by mickiii** [monterail/vue-multiselect#526]
I am sure this is a simple thing, but I can't seem to figure it out from the docs. How do I set the initial value and label for an input like the example "Asynchronous select". 

Thanks in advance!

**Comment by shentao** [comment]
Do I understand you correctly? You want to have a preselected value inside the dropdown, that is not yet available in the options? It’s not in the options because it’s an async component.
In that case, you need to pass an object/array inside as the `value` / `v-model` that match the same structure as the options.

In other words, Vue-Multiselect does not need the options array to contain an element to display it if it exists in the `value` prop. 

For example, your data model could look like this:
```
{
  selectedCountries: [{ name: 'Poland', code: 'PL' }],
  countries: []
}
```
