### ISSUE TITLE
Custom remove from `:options`

### ISSUE THREAD

**Issue by gabrielchase** [monterail/vue-multiselect#527]
Anyway we can access/override the remove function in the multiple select (`:multiple="true"`)?

**Comment by shentao** [comment]
You can’t override it but you can use the `@select` and `@remove` events to detect the events and react to them yourself rather than rely on `v-model`/`@input`. This way you can mutate the selected options yourself and VueMultiselect will reflect those changes (it will override the `internalValue` if you change the `value` prop.
