### ISSUE TITLE
Put styles to component

### ISSUE THREAD

**Issue by glutaminefree** [monterail/vue-multiselect#552]
Hi!
Great library! Thanks!

I think - why we need add css file on page in manual mode, when you can just put it inside component?
Your component builded with vue single file component. And it support css inside component.

**Comment by shentao** [comment]
I know :) This is how it was previously. However, this makes it much harder to override those styles. Having it in a separate file makes it easy to customize without the need to override all the styles as you can provide your own version of those. it should also help to cache the CSS.
Sure it might be a bit troublesome I know. If you want to have the styles inside the component, you can always import the source files.
```
import Multiselect from 'vue-multiselect/src/Multiselect.vue'
```

**Comment by superrandres** [comment]
Hello, I have tried the way to import the component that quotes but in my browser it conflicts with the styles of uikit. Please help me to correct it so that it looks like the demo.
`import Multiselect from 'vue-multiselect/src/Multiselect.vue'`
I'm also putting scoped on the style label.
`<style lang="css" scoped="">`
![image](https://user-images.githubusercontent.com/8306417/32971608-f27de070-cbbb-11e7-9f4d-6d24d38d7f17.png)
