### ISSUE TITLE
No styles when using Vueify?

### ISSUE THREAD

**Issue by theplankmeister** [monterail/vue-multiselect#553]
This can't be demonstrated using JSFiddle... So I made a repo demonstrating the issue:

https://github.com/theplankmeister/vue-multiselect-demo

The problem is that the styling in the Multiselect component is not being imported into the Vueified output. I'm not sure this can be a problem with Vueify, because, as shown, another component with an included style block is correctly having its CSS exported.

**Comment by shentao** [comment]
Please take a look at the docs. If you’re importing the already compiled version:
```
import Multiselect from 'vue-multiselect'
```
the styles are not imported. This is because the styles are extracted into a separate css file. You have to import the styles yourself. See the basic usage section: https://monterail.github.io/vue-multiselect/#sub-getting-started

The reasoning behind this is that it makes it easier to cache the styles and also makes it possible to completely replace all the styles with custom ones without the need to override the CSS.

If you, however, import the non-compiled version (the `.vue` file) it still includes the CSS.
